### ISSUE TITLE
Dependency on tslib because of the importHelpers option

### ISSUE THREAD

**Issue by sa3dany** [shuizhongyueming/rollup-plugin-output-manifest#2]
This plugin has a dependency on the [tslib](https://github.com/Microsoft/tslib) package because `importHelpers` is enabled in `tsconfig.json`.

Is it better to keep this dependency but mention this in the readme or to disable the `importHelpers` option?

**Comment by shuizhongyueming** [comment]
Sorry for the response so late.

Thank you for the suggestion, and I have fix the dependency in the latest release
